In [21]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.model_selection import train_test_split


In [22]:
data=pd.read_csv("/content/IRIS.csv")

In [23]:
X=data.drop("species",axis=1)
y=data["species"]

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# Corrected the order of variables assigned from train_test_split
model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [29]:
accuracy=accuracy_score(y_test,y_pred)
print(f"Accuracy:{accuracy}")

Accuracy:1.0


In [30]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
